### ISSUE TITLE
Ability to set margin, padding, and border on the Social buttons

### ISSUE THREAD

**Issue by TAjgriffin** [ndiego/social-sharing-block#27]
Currently the block only supports margin, padding, and borders on the main block. There are use cases where someone may need to apply them to the icon buttons themself rather than the outer block.

Current:
![image](https://github.com/ndiego/social-sharing-block/assets/88406427/8e2776e9-1f8a-40d2-81b3-b4b3b5ba21a5)

Desired:
![image](https://github.com/ndiego/social-sharing-block/assets/88406427/80200ea4-7bba-4f01-abfd-0885177e9012)

**Comment by ndiego** [comment]
#28 has been merged, so closing this. Thanks again for the PR!
