### ISSUE TITLE
Add YouTube and RSS Icons

### ISSUE THREAD

**Issue by TheJeffr0** [ndiego/social-sharing-block#34]
Any chance you could add YouTube and RSS icons? Here's an example. 
<img width="238" alt="Screenshot 2024-11-07 at 8 53 06 PM" src="https://github.com/user-attachments/assets/ee55c230-dc88-4cee-b944-74ba09320d84">

**Comment by ndiego** [comment]
From my understanding, you cannot share a link to YouTube or RSS. Happy to be proven wrong if there is a solution out there. 

If you just need to provide a link to a YouTube channel or RSS feed, you could use the Core Social Icons block.

**Comment by TheJeffr0** [comment]
I ended up using the Core Social Icons block :D Thanks!
